### ISSUE TITLE
Errors in latest unity 2021 2

### ISSUE THREAD

**Issue by nigelmerle** [soupday/cc_unity_tools_HDRP#20]
NullReferenceException: Object reference not set to an instance of an object
Reallusion.Import.Pipeline.AddDiffusionProfilesHDRP () (at Assets/_Game/cc3_unity_tools_HDRP-0.1.8b/Editor/Pipeline.cs:366)
Reallusion.Import.Importer.Import () (at Assets/_Game/cc3_unity_tools_HDRP-0.1.8b/Editor/Importer.cs:119)
Reallusion.Import.ImporterWindow.ImportCharacter (Reallusion.Import.CharacterInfo info, Reallusion.Import.MaterialQuality quality) (at Assets/_Game/cc3_unity_tools_HDRP-0.1.8b/Editor/ImporterWindow.cs:586)
Reallusion.Import.ImporterWindow.OnGUIActionArea (UnityEngine.Rect actionBlock) (at Assets/_Game/cc3_unity_tools_HDRP-0.1.8b/Editor/ImporterWindow.cs:502)
Reallusion.Import.ImporterWindow.OnGUI () (at Assets/_Game/cc3_unity_tools_HDRP-0.1.8b/Editor/ImporterWindow.cs:281)
UnityEditor.HostView.InvokeOnGUI (UnityEngine.Rect onGUIPosition) (at <12f9706bdb064a6c8a1d1b6f565a0097>:0)
UnityEditor.DockArea.DrawView (UnityEngine.Rect dockAreaRect) (at <12f9706bdb064a6c8a1d1b6f565a0097>:0)
UnityEditor.DockArea.OldOnGUI () (at <12f9706bdb064a6c8a1d1b6f565a0097>:0)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <0713f2bf9762492888a6ba6ef8e57ae8>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <0713f2bf9762492888a6ba6ef8e57ae8>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <0713f2bf9762492888a6ba6ef8e57ae8>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Boolean canAffectFocus) (at <0713f2bf9762492888a6ba6ef8e57ae8>:0)
UnityEngine.UIElements.IMGUIContainer.SendEventToIMGUIRaw (UnityEngine.UIElements.EventBase evt, System.Boolean canAffectFocus, System.Boolean verifyBounds) (at <0713f2bf9762492888a6ba6ef8e57ae8>:0)
UnityEngine.UIElements.IMGUIContainer.SendEventToIMGUI (UnityEngine.UIElements.EventBase evt, System.Boolean canAffectFocus, System.Boolean verifyBounds) (at <0713f2bf9762492888a6ba6ef8e57ae8>:0)
UnityEngine.UIElements.IMGUIContainer.HandleEvent (UnityEngine.UIElements.EventBase evt) (at <0713f2bf9762492888a6ba6ef8e57ae8>:0)
UnityEngine.UIElements.CallbackEventHandler.HandleEventAtTargetPhase (UnityEngine.UIElements.EventBase evt) (at <0713f2bf9762492888a6ba6ef8e57ae8>:0)
UnityEngine.UIElements.MouseCaptureDispatchingStrategy.DispatchEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <0713f2bf9762492888a6ba6ef8e57ae8>:0)
UnityEngine.UIElements.EventDispatcher.ApplyDispatchingStrategies (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, System.Boolean imguiEventIsInitiallyUsed) (at <0713f2bf9762492888a6ba6ef8e57ae8>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <0713f2bf9762492888a6ba6ef8e57ae8>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEventQueue () (at <0713f2bf9762492888a6ba6ef8e57ae8>:0)
UnityEngine.UIElements.EventDispatcher.OpenGate () (at <0713f2bf9762492888a6ba6ef8e57ae8>:0)
UnityEngine.UIElements.EventDispatcherGate.Dispose () (at <0713f2bf9762492888a6ba6ef8e57ae8>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <0713f2bf9762492888a6ba6ef8e57ae8>:0)
UnityEngine.UIElements.EventDispatcher.Dispatch (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, UnityEngine.UIElements.DispatchMode dispatchMode) (at <0713f2bf9762492888a6ba6ef8e57ae8>:0)
UnityEngine.UIElements.BaseVisualElementPanel.SendEvent (UnityEngine.UIElements.EventBase e, UnityEngine.UIElements.DispatchMode dispatchMode) (at <0713f2bf9762492888a6ba6ef8e57ae8>:0)
UnityEngine.UIElements.UIElementsUtility.DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel panel) (at <0713f2bf9762492888a6ba6ef8e57ae8>:0)
UnityEngine.UIElements.UIElementsUtility.UnityEngine.UIElements.IUIElementsUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& eventHandled) (at <0713f2bf9762492888a6ba6ef8e57ae8>:0)
UnityEngine.UIElements.UIEventRegistration.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at <0713f2bf9762492888a6ba6ef8e57ae8>:0)
UnityEngine.UIElements.UIEventRegistration+<>c.<.cctor>b__1_2 (System.Int32 i, System.IntPtr ptr) (at <0713f2bf9762492888a6ba6ef8e57ae8>:0)
UnityEngine.GUIUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& result) (at <747b78853467428797e4a32ad808a642>:0)

**Comment by soupday** [comment]
2021.2 uses HDRP 12.0.0, which has moved the diffusion profile list location to another asset, and there are some other incompatibilities.

I've made a 2021.2 [branch](https://github.com/soupday/cc3_unity_tools_HDRP/tree/2021.2) and [release](https://github.com/soupday/cc3_unity_tools_HDRP/releases/tag/0.2.1-hdrp12)

It does also look like there are some bugs in HDRP 12.0.0. e.g. the HDRP/Hair shader seems broken and the Visual environment volume overrides has issues.

**Comment by nigelmerle** [comment]
Do you advise me to downgrade hdrp?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by soupday** [comment]
As always with Unity it's a question of: Are you prepared to live with it being a bit buggy until the issues are fixed. As it's the very first version of HDRP 12, I imagine it will get fixed fairly quickly.

For the most part it seems to work. Only the preview scene has some problems with the global volumes, but that isn't a real scene and I may just be doing it wrong. The master shader nodes appear to work, and that's the important part.

**Comment by nigelmerle** [comment]
Alright yeah I know, I am stuck for two days with this new unity, I am stuck  with reimports loops, freezes and hold on messages. Today it took me more than three hours to import a project.
I am looking all over internet but I could not find any good fixes. Do you have any advice?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by soupday** [comment]
Seems to be the HDRP pipeline that causes all the progress bar freezing and hanging. I Don't see any of this in URP or Built-in.

But in my development projects I've turned the HDRP quality down to medium or low and see far less hanging and freezes. By default it's jacked up to high and hangs so much it's almost unusable.

**Comment by nigelmerle** [comment]
I will try to reinstall hdrp and see how it goes

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by nigelmerle** [comment]
I think i want to try urp now to see the difference, which version of cc3
unity tool do i need to use?

**Comment by soupday** [comment]
https://github.com/soupday/cc3_unity_tools_URP

**Comment by nigelmerle** [comment]
Thank you

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
