### ISSUE TITLE
Publishing an exe in Unity 2021.3.6f1 results in errors

### ISSUE THREAD

**Issue by YulesRules** [soupday/cc_unity_tools_HDRP#49]
**_(Unity 2021.3.6f1)_**
**_(HDRP Version 12.1.7 - June 30, 2022)_**
**_(CC/iC Unity Tools HDRP Version 1.3.5)_**

_Tried with, and without, cloth physics - no extra features_ 

So close! :] I have a wonderful Unity editor preview of my CC4 character waltzing around with cloth physics but, when attempting to publish as a windows build the following errors appear:

![error_log](https://user-images.githubusercontent.com/110333307/182022308-2ba895c6-8b64-4a8b-a237-38c74a2f2fd5.jpg)

In text:

> D:\Virtual Autonomy\Character Studio Exports\Unity Stuff\cc_unity_tools_HDRP-1.3.5\Runtime\PhysicsSettingsStore.cs(7,56): error CS0426: The type name 'PhysicsSettings' does not exist in the type 'WeightMapper'

> D:\Virtual Autonomy\Character Studio Exports\Unity Stuff\cc_unity_tools_HDRP-1.3.5\Runtime\PhysicsSettingsStore.cs(8,60): error CS0426: The type name 'ColliderSettings' does not exist in the type 'ColliderManager'

> Error building Player because scripts had compiler errors

> Build completed with a result of 'Failed' in 2 seconds (2433 ms) UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

 

> UnityEditor.BuildPlayerWindow+BuildMethodException: 3 errors at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (UnityEditor.BuildPlayerOptions options) [0x002da] in <44a70d1b13cf47e29810e30f45ffae08>:0  at UnityEditor.BuildPlayerWindow.CallBuildMethods (System.Boolean askForBuildLocation, UnityEditor.BuildOptions defaultBuildOptions) [0x00080] in <44a70d1b13cf47e29810e30f45ffae08>:0 UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

Any ideas? :] You've made for **_an awesome workflow_**, just need to get over this hurdle.

[Forum post here.](https://forum.reallusion.com/FindPost521115.aspx)

https://user-images.githubusercontent.com/110333307/182022755-8a15dd51-5558-4b1c-b124-f47daadfb3b4.mp4

**Comment by soupday** [comment]
I Forgot the compiler directives for the PhysicsSettingsStore.

The three runtime components are really only helper scripts for Playmode adjustments in the editor, so for builds they are just meant to be empty scripts. But this one wasn't.

Try the new release. It should fix it.

**Comment by YulesRules** [comment]
That fixed it, thank you very much. :]
