### ISSUE TITLE
Import tool doesn't work anymore? 

### ISSUE THREAD

**Issue by gekidoslair** [soupday/cc_unity_tools_HDRP#62]
Used to use this a ton, just updated to the latest version and it gives me nothing but errors now? Not sure what's up.

First it spits this error
![error](https://user-images.githubusercontent.com/4552687/208281952-ceb2829a-2bb4-42d3-a053-c40560d18613.png)

The error logs are the following:

```
Cannot open file 'Assets/Game/Content/Characters/business-people-vol-6-415933/business-m-0013/Materials/business-m-0013-415932.meta' for write.

UnityEngine.StackTraceUtility:ExtractStackTrace ()
Reallusion.Import.Util:CreateFolder (string,string) (at D:/projects/_PixelWizardsPackages/cc3_unity_tools_HDRP/Editor/Util.cs:275)
Reallusion.Import.Importer:.ctor (Reallusion.Import.CharacterInfo) (at D:/projects/_PixelWizardsPackages/cc3_unity_tools_HDRP/Editor/Importer.cs:170)
Reallusion.Import.ImporterWindow:ImportCharacter (Reallusion.Import.CharacterInfo) (at D:/projects/_PixelWizardsPackages/cc3_unity_tools_HDRP/Editor/ImporterWindow.cs:1107)
Reallusion.Import.ImporterWindow:BuildCharacter () (at D:/projects/_PixelWizardsPackages/cc3_unity_tools_HDRP/Editor/ImporterWindow.cs:1177)
UnityEditor.EditorApplication:Internal_CallDelayFunctions ()
```

Then 
```
Failed to write meta file 'Assets/Game/Content/Characters/business-people-vol-6-415933/business-m-0013/Materials/business-m-0013-415932.meta'
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Reallusion.Import.Util:CreateFolder (string,string) (at D:/projects/_PixelWizardsPackages/cc3_unity_tools_HDRP/Editor/Util.cs:275)
Reallusion.Import.Importer:.ctor (Reallusion.Import.CharacterInfo) (at D:/projects/_PixelWizardsPackages/cc3_unity_tools_HDRP/Editor/Importer.cs:170)
Reallusion.Import.ImporterWindow:ImportCharacter (Reallusion.Import.CharacterInfo) (at D:/projects/_PixelWizardsPackages/cc3_unity_tools_HDRP/Editor/ImporterWindow.cs:1107)
Reallusion.Import.ImporterWindow:BuildCharacter () (at D:/projects/_PixelWizardsPackages/cc3_unity_tools_HDRP/Editor/ImporterWindow.cs:1177)
UnityEditor.EditorApplication:Internal_CallDelayFunctions ()
```
and
`Assertion failed on expression: 'outputHash.IsValid()'
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Reallusion.Import.Util:CreateFolder (string,string) (at D:/projects/_PixelWizardsPackages/cc3_unity_tools_HDRP/Editor/Util.cs:275)
Reallusion.Import.Importer:.ctor (Reallusion.Import.CharacterInfo) (at D:/projects/_PixelWizardsPackages/cc3_unity_tools_HDRP/Editor/Importer.cs:170)
Reallusion.Import.ImporterWindow:ImportCharacter (Reallusion.Import.CharacterInfo) (at D:/projects/_PixelWizardsPackages/cc3_unity_tools_HDRP/Editor/ImporterWindow.cs:1107)
Reallusion.Import.ImporterWindow:BuildCharacter () (at D:/projects/_PixelWizardsPackages/cc3_unity_tools_HDRP/Editor/ImporterWindow.cs:1177)
UnityEditor.EditorApplication:Internal_CallDelayFunctions ()
`

I can see that it created the materials folder, but nothing inside it, and if I select the mesh itself afterwards for the character I can see that the materials on it are whacked:

![character](https://user-images.githubusercontent.com/4552687/208282056-75505250-9a9a-492c-8088-02d644668e48.png)

This is in Unity 2021.3.10f1 (the LTS version) and the HDRP importer 1.4.2

Any ideas?

**Comment by soupday** [comment]
Unity can't write a meta file.

Unity handles meta file creation internally so if it can't write one, then it's most likely file system problem.

It could just be something has locked the meta file in question and won't let anything write to it, or it could be an indication of a serious problem with the hard drive, or the hard drive is full?

Find the meta file in file explorer and delete it, if it exists. See if that fixes it. Rebooting should free any file system locks on it.

If not you may also want to check your hard drive for file system / hardware errors.

**Comment by gekidoslair** [comment]
not sure what the issue was but it's working now - thanks!
