### ISSUE TITLE
Unity hair shader

### ISSUE THREAD

**Issue by wilg** [soupday/cc_unity_tools_HDRP#66]
Would using the HDRP hair shader achieve better results? https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@14.0/manual/hair-shader.html

**Comment by soupday** [comment]
It does use the HDRP hair shader.

**Comment by wilg** [comment]
I see, it's inside the shader graph. I was confused because I was looking for HDRP/Hair as the shader. Perhaps the issue was https://github.com/soupday/cc_unity_tools_HDRP/issues/68#issuecomment-1412841625
